os: windows
language: node_js
node_js: stable
cache: pnpm

install:
  - pnpm install

script:
  - pnpm make
    
deploy: 
  provider: releases
  file: out/make/**/*.exe
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true